### ISSUE TITLE
Chrome autofill makes WSR `<Input />` looks bad

### ISSUE THREAD

**Issue by BnayaZil** [wix/wix-style-react#4959] opened 2020-02-05 14:12 UTC
# 🐛 Bug Report

### 🏗 Relevant Components

`<Input />`

### 😯 Current Behavior

Chrome autofill makes WSR `<Input />` looks bad
![image](https://user-images.githubusercontent.com/13505136/73849062-ecb36a80-4831-11ea-8f52-cca551948405.png)

### 🤔 Expected Behavior

To look good

### 👣 Steps to Reproduce

Have input with name "email" / "password" in a domain that u have saved credintials

### 👀 Severity

- Major

**Comment by etaybarzilay89** [comment] 2020-02-09 08:19
Happens for me two.
Here are some instructions to enable auto complete and reproduce the bug:

1. Define auto complete in chrome like showed in the picture. (https://wix.slack.com/files/U5XTCBY9K/FTM1Q9W4U/image.png)
2. Try to write the first letter of your new auto complete in the input and accept the auto complete.

Result: you'll see that input layout breaks. (It looks like the new Input component has padding top and bottom of 6px that does not exists in WSR version 6 Input component.

**Comment by BnayaZil** [comment] 2020-02-16 08:10
Ping

**Comment by shlomitc** [comment] 2020-02-16 09:25
A simple reproducible example:

![image](https://user-images.githubusercontent.com/6093192/74602075-c1d8da00-50ad-11ea-99a3-953fa5253e30.png)
```jsx
<Box>
  <Input name="email"/>
</Box>
```

And a short article about customizing autofill styles:
https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/

I'll add this to our backlog but it's somewhat low priority. You can wait for a fix (no ETA at the moment), or contribute a fix. Thanks

**Comment by EgoziE** [comment] 2021-01-19 16:13
Moved to Jira - closing

**Closed by EgoziE** 2021-01-19 16:13 UTC
Labels: Bug
