### ISSUE TITLE
<ButtonWithOptions/> - Two chevron icons appear in story

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#2204] opened 2018-09-05 13:16 UTC
### Summary:
when I pick a set of parameters as seen in the screenshot below, after selecting one of the options, a second chevron icon appears

### Priority: Normal

![image](https://user-images.githubusercontent.com/29533829/45095505-e134af00-b126-11e8-82a9-7656138b3e4a.png)

**Comment by hepiyellow** [comment] 2018-09-17 17:15
@naamagr 
Hi, 
Thanks for reporting.
I could not reproduce this.
Could you try and reproduce it here [codesandbox](https://codesandbox.io/s/mymk2zn1mp)?

**Comment by shlomitc** [comment] 2018-09-17 18:46
@hepiyellow - it was reproduced in the story, did you set the exact same settings as in the attached picture?

**Comment by hepiyellow** [comment] 2018-09-17 19:12
Yes i did.

**Comment by YuriyFedorov** [comment] 2018-10-16 12:12
Hey

Any updates on that? 

thanks

**Comment by wuwa** [comment] 2018-10-17 07:43
there is a spec for this: zpl.io/aMdwdNr
however this whole component is a bad mix of things in my opinion.
maybe a good time to rewrite it.

**Comment by naamagr** [comment] 2018-10-17 07:52
Indeed, we want to see a ChevronDown arrow before an option is selected (and at all times), to indicate that is it a drop down.
I've just figured it out though! if you pass selectedId to ButtonWithOptions that is actually one of the options (not -1 like in the example), the arrow will always appear (even before selecting anything).

**Comment by hepiyellow** [comment] 2018-10-18 09:53
@naamagr So can I close this issue?

**Comment by naamagr** [comment] 2018-10-18 13:28
I think so

**Closed** 2018-10-18 13:34 UTC
Labels: ButtonWithOptions, Docs
