### ISSUE TITLE
<AutoComplete withArrow={false} /> renders with an arrow

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#5486] opened 2020-05-21 07:49 UTC
# 🐛 Bug Report

### 🏗 Relevant Components
`<AutoComplete/>`
...

### 😯 Current Behavior

`<AutoComplete withArrow={false} />` renders with an arrow
...

### 🤔 Expected Behavior
arrow should be hidden
...

### 👣 Steps to Reproduce
broken in wsr storybook,
also, you can write in the playground `<AutoComplete withArrow={false} />`

### 👀 Severity
- Major

**Comment by EgoziE** [comment] 2020-05-24 07:17
duplicate of - https://github.com/wix/wix-style-react/issues/4919
closing

**Closed by EgoziE** 2020-05-24 07:17 UTC
