### ISSUE TITLE
[Tooltip] - examples with bugs 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4435] opened 2019-11-01 10:23 UTC
# Tooltip documentation issue

### 🔦 Scope

Issue on [main tab](https://wix-style-react.now.sh/?activeTab=Description&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=Tooltip&stories=1). I think, related to #4242: 
![image](https://user-images.githubusercontent.com/8848858/68018277-6a029880-fca1-11e9-9d59-6e23bbb6e2e3.png)

Issues in [playground](https://wix-style-react.now.sh/?activeTab=Playground&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=Tooltip&stories=1):

![image](https://user-images.githubusercontent.com/8848858/68016465-52291580-fc9d-11e9-923c-2521e48577ce.png)

![image](https://user-images.githubusercontent.com/8848858/68018466-e39a8680-fca1-11e9-848b-d5e4b1f83eab.png)

### 💁 Explanation

Examples are broken

### 👀 Severity

- Major

WSR version 7.12.0

**Comment by mykas** [comment] 2019-11-01 17:09
Hi, regarding the tooltip functionality in appendTo="parent". The example might be looking wrong but functionality is working as aspected. Appending to parent basically means that tooltip content calculates its width based on trigger elements size. Appending to parent is not the best solution for tooltip but for popover component there are cases. The other example where tooltip is not able to point directly on the trigger element is kind a harder problem but only occurs on certain situation. The issue occurs when parent container width is expanded to 100% and the trigger element is display block. Usually this happens when used with css grid with direct childs that are tooltip. This issue is still under discussion on how to solve it. I am closing this issue because one example is as intended and another is know bug in another issue.

**Closed by mykas** 2019-11-01 17:09 UTC
Labels: Docs, Tooltip

**Comment by rudnitskih** [comment] 2019-11-03 12:53
Thank you!
