### ISSUE TITLE
<Breadcrumbs /> breadcrumbs with long names behave weirdly in Firefox

### ISSUE THREAD

**Issue by neta-hemyan** [wix/wix-style-react#3087] opened 2019-03-11 14:24 UTC
# 🐛 Bug Report

### 😯 Current Behavior

When trying to add a breadcrumb item with a long name, this happens in Firefox: 
![Screen Shot 2019-03-11 at 16 12 57](https://user-images.githubusercontent.com/39234978/54130233-b2223180-4418-11e9-972a-5bc614238da4.png)

In chrome the item is just cut:
![Screen Shot 2019-03-11 at 16 14 47](https://user-images.githubusercontent.com/39234978/54130392-f6153680-4418-11e9-9b71-452c4231a76a.png)

### 🤔 Expected Behavior

The item should cut if it's bigger than a certain width, and we should see ellipsis.

### 👣 Steps to Reproduce

The bug was reproduced using https://wix-wix-style-react.surge.sh/?activeTab=Usage&addons=0&full=0&panelRight=0&selectedKind=6.%20Navigation&selectedStory=6.2%20Breadcrumbs&stories=1

and Chrome/Firefox developer tools to change the items' names.

### 👀 Severity

My QA dev classified it as Major.

**Comment by splintor** [comment] 2019-12-01 12:27
Some comments:
1. The [repro link](https://wix-wix-style-react.surge.sh/?activeTab=Usage&addons=0&full=0&panelRight=0&selectedKind=6.%20Navigation&selectedStory=6.2%20Breadcrumbs&stories=1) seems to be outdated. Here is [an updated link](https://wix-style-react.now.sh/?activeTab=Description&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=Breadcrumbs&stories=1).

1. No need for dev tools. In WSR description tab, you can click `Show Source` for any of the examples, and then edit the sample code and see the results immediately.

1. The problem is also in Chrome. Indeed, it doesn't show that the line breaks in the internal `<Text>`, but because that is what happen, it doesn't show ellipsis, and it doesn't show a tooltip when hovering over it.

1. I tried to write a PR to fix it by adding `ellipsis` to [the internal `<Text>`](https://github.com/wix/wix-style-react/blob/master/src/Breadcrumbs/Breadcrumbs.js#L71), but this caused all the breadcrumbs to be aligned to the top of the chevron, because of [this CSS line](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/hocs/EllipsedTooltip/Text.st.css#L6), so I don't know what is the correct fix for that.

**Comment by splintor** [comment] 2019-12-01 12:29
@shlomitc Now that we plan to put folder names in breadcrumbs, can the priority of this bug be increased? We will certainly need it fixed. I'd love to do it, but I might need your guidance (see my previous comment).

**Comment by EgoziE** [comment] 2019-12-01 14:41
Hey @splintor 
Adding an `ellipsis` to the inner text requires some thought
We need to pay attention to the spec in Zeplin
 
1. When all steps together are longer than the container, all steps that are **longer** than the average width should have an ellipsis and be the same width.
2. When there's an **active** step, it should not have ellipsis.
3. When all the items get to minimum size (36px) Start show ellipsis on the active step (the last).

Note!
There's a current bug related to <Text/> that the makes it's tooltip wrapper too high (https://github.com/wix/wix-style-react/issues/4606)
As you noticed, in this case, `<Breadcrumbs/>` component has a wrapper of 30px in line-height, this makes the text  to be aligned to the top of the chevron.

I'll see if we can increase the priority of this bug.
Meanwhile, I added more visual tests to cover more cases, including long text.

**Comment by splintor** [comment] 2019-12-01 15:24
Thanks @EgoziE 
Where can I see the Zeplin spec?

Please note that I need to start working on adding a "collapsible" feature to `<Breadcrumbs>` - see https://zpl.io/2j7r43A and https://zpl.io/bzj9WD8. Who should I discuss related issues with?

**Comment by EgoziE** [comment] 2019-12-01 15:46
This is our spec: https://zpl.io/2ZDM4xq
Um.. as you can see, the "collapse" functionality you're talking about, as well as the ellipsis are marked as **Not Yet Developed**.
There's much work to be done there.

I'll bring this subject up at our next team meeting

**Comment by splintor** [comment] 2019-12-01 15:49
Opened a Feature Request for it - https://github.com/wix/wix-style-react/issues/4629

**Comment by splintor** [comment] 2019-12-01 15:54
If we have collapsible breadcrumbs, we never need to collapse to "ellipsis" only.

I understand I will need to develop the "collapsible" feature. I just want to have a WSR contact I can discuss issues I face while developing it (like I had @nitayneeman when I developed features for `<Table>` selection)

**Comment by EgoziE** [comment] 2019-12-01 20:20
@splintor I'm available for questions and reviews for the next couple of weeks (1-12 December)

In addition to the _menu feature_ request you opened,
I'm closing this issue, opening a feature request for _ellipsis_ (without menu).

**Closed by EgoziE** 2019-12-01 20:20 UTC
Labels: <Breadcrumbs/>, Bug, Priority: Low
