### ISSUE TITLE
<Page.Header> link is wrong

### ISSUE THREAD

**Issue by jurasm** [wix/wix-style-react#3103] opened 2019-03-14 09:57 UTC
# 🐛 Bug Report

### 🏗 Relevant Components
<Page>

### 😯 Current Behavior

In documentation for <Page> link to <Page.Header> is wrong.

### 🤔 Expected Behavior

Should navigate to <Page.Header> documentation

### 👣 Steps to Reproduce
Go to Page Layout storybook and press on <Page.Header> link.
https://wix-wix-style-react.surge.sh/?selectedKind=2.%20Layout&selectedStory=2.1%20Page%20Layout&full=0&addons=0&stories=1&panelRight=0

### 👀 Severity

- Low

**Comment by argshook** [comment] 2019-04-01 11:30
closing, duplicate of https://github.com/wix/wix-style-react/issues/3006 in progress

**Closed by argshook** 2019-04-01 11:30 UTC
Labels: Docs, type:bug
