### ISSUE TITLE
<Button /> <IconButton /> and <TextButton /> render issue in EDGE44+

### ISSUE THREAD

**Issue by wasabiru** [wix/wix-style-react#2999] opened 2019-02-20 09:30 UTC
Hi, I found some issue with using different types of buttons in one render function.
Example (order of elements is not important)
`
<TextButton>Text</TextButton>
<IconButton><More /></IconButton>
<Button>Text</Button>`
If I use this code, EDGE is render only **first** element in right way and others wont have css-classes and will be render as default browser buttons. If I repeat elements something like this 
`
<TextButton>Text</TextButton>
<IconButton><More /></IconButton>
<TextButton>Text</TextButton>
<Button>Text</Button>`
Edge will render both **TextButton** in right way, but still only that type of buttons, which stays in first place.

![edge44](https://user-images.githubusercontent.com/47810906/53081083-8693e180-3513-11e9-8869-50b688352edf.png)

I have fixed this in my case by using ButtonNext from wix-ui-core directly but I think, this is not good:)

**Comment by shlomitc** [comment] 2019-02-20 10:45
I checked the [IconButton](https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.2%20IconButton&full=0&addons=0&stories=1&panelRight=0) story in the storybook in Edge and they look ok. can you please check it from your side?

**Comment by wasabiru** [comment] 2019-02-20 11:53
> I checked the [IconButton](https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.2%20IconButton&full=0&addons=0&stories=1&panelRight=0) story in the storybook in Edge and they look ok. can you please check it from your side?

Yes, it's ok. Like other button types in storybook. The problem not in one component, but in using different button types in one render function. If you want render 3 <Button />, you will be ok. But if you want use 2 or 3 types like <IconButton/><Button /><Button /><IconButton /> - first and other similar will render Ok, but second and other - will be render without specific css-classes.

Please, check this example https://d1howb1wwyap5o.cloudfront.net/tmp/wix-style-react/index.html which consists of following code 
```
render() {
	return (
		<div>
			<Button>
				Text
			</Button>
			<IconButton>
				<More />
			</IconButton>
			<TextButton>
				Text
			</TextButton>
			<Button>
				Text
			</Button>
			<IconButton>
				<More />
			</IconButton>
			<TextButton>
				Text
			</TextButton>
		</div>
	);
}
```

**Comment by shlomitc** [comment] 2019-02-20 12:17
looks ok on my machine. I suspect some caching issues.
can you try to clear cache and see if it helps?

**Comment by wasabiru** [comment] 2019-02-20 12:28
Unfortunately, this bug still with us. 
I reproduce it on my device an in browserStack  https://monosnap.com/file/FnzUTORHRg6Qqjgpq6bb2PgWDZWdbq

Some details, that I found out:
- EDGE 42 - ok EDGE 44 - not ok
- If I open developer tools and refresh, it will be ok and all future resreshes also ok. But if I open new tab with this example, it wont be ok. And  reason is not in cache, because in my example I use definitely new URL to all static sources.

**Comment by mykas** [comment] 2019-02-20 12:33
Can we get some kind of browserStack example to try ourselves?

**Comment by wasabiru** [comment] 2019-02-20 12:59
> Can we get some kind of browserStack example to try ourselves?

It's simple. Just go to https://www.browserstack.com, create free trial account and try my example on Windows 10 + Edge 18 (Microsoft Edge 44.17763.1.0)

Also I attach result HTML from Edge on real device - You can see missing css-classes such as `iconbutton1031662007--iconButton`

```<div><button tabindex="0" class="buttonnext656424613--root Focusable2326836241--root button849830051--button"><span class="buttonnext656424613--content">Text</span></button><button tabindex="0" class="buttonnext656424613--root Focusable2326836241--root" aria-disabled="false"><span class="buttonnext656424613--content"><svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" width="24px" height="24px"><path d="M 6 12.5 C 6 11.6716 6.6658 11 7.5 11 C 8.32843 11 9 11.6658 9 12.5 C 9 13.3284 8.3342 14 7.5 14 C 6.67157 14 6 13.3342 6 12.5 Z M 11 12.5 C 11 11.6716 11.6658 11 12.5 11 C 13.3284 11 14 11.6658 14 12.5 C 14 13.3284 13.3342 14 12.5 14 C 11.6716 14 11 13.3342 11 12.5 Z M 16 12.5 C 16 11.6716 16.6658 11 17.5 11 C 18.3284 11 19 11.6658 19 12.5 C 19 13.3284 18.3342 14 17.5 14 C 16.6716 14 16 13.3342 16 12.5 Z" /></svg></span></button><button tabindex="0" class="buttonnext656424613--root Focusable2326836241--root" aria-disabled="false"><span class="buttonnext656424613--content">Text</span></button><button tabindex="0" class="buttonnext656424613--root Focusable2326836241--root button849830051--button"><span class="buttonnext656424613--content">Text</span></button><button tabindex="0" class="buttonnext656424613--root Focusable2326836241--root" aria-disabled="false"><span class="buttonnext656424613--content"><svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" width="24px" height="24px"><path d="M 6 12.5 C 6 11.6716 6.6658 11 7.5 11 C 8.32843 11 9 11.6658 9 12.5 C 9 13.3284 8.3342 14 7.5 14 C 6.67157 14 6 13.3342 6 12.5 Z M 11 12.5 C 11 11.6716 11.6658 11 12.5 11 C 13.3284 11 14 11.6658 14 12.5 C 14 13.3284 13.3342 14 12.5 14 C 11.6716 14 11 13.3342 11 12.5 Z M 16 12.5 C 16 11.6716 16.6658 11 17.5 11 C 18.3284 11 19 11.6658 19 12.5 C 19 13.3284 18.3342 14 17.5 14 C 16.6716 14 16 13.3342 16 12.5 Z" /></svg></span></button><button tabindex="0" class="buttonnext656424613--root Focusable2326836241--root" aria-disabled="false"><span class="buttonnext656424613--content">Text</span></button></div>```

**Comment by shlomitc** [comment] 2019-02-20 14:27
@tomrav - please be aware of it. Can you try to reproduce this on your machines and see if it's a general `stylable` issue?

**Comment by barak007** [comment] 2019-02-20 15:11
Where is this example project? so we can run it locally
https://d1howb1wwyap5o.cloudfront.net/tmp/wix-style-react/index.html

**Comment by wasabiru** [comment] 2019-02-21 05:38
Please, use this project [wix-style-react-edge44.tar.gz](https://github.com/wix/wix-style-react/files/2887801/wix-style-react-edge44.tar.gz)

**Comment by shlomitc** [comment] 2019-02-21 18:20
@barak007 - any interesting findings?

**Comment by shlomitc** [comment] 2019-02-26 14:04
looks like an issue in the new edge version due to a bug in their engine. @barak007 says there is a workaround they can do which will be released in their next version

**Comment by tomrav** [comment] 2019-02-26 15:42
Here's the [issue](https://github.com/Microsoft/ChakraCore/issues/5970) we've opened with ChakraCore.

Our workaround version should be released soon.

**Comment by tomrav** [comment] 2019-02-27 11:11
We've released a [new version](https://github.com/wix/stylable/releases/tag/%40stylable%2Fruntime%401.0.3) of our runtime (`v1.0.4`) that includes the workaround.

**Comment by shlomitc** [comment] 2019-02-27 11:33
@wasabiru - please confirm that issue is resolved

**Comment by wasabiru** [comment] 2019-02-27 12:15
Yes, all button are ok. Thanks!

**Closed** 2019-02-27 12:33 UTC
Labels: Button, bug
