### ISSUE TITLE
`<MessageBoxFunctionalLayout/>` - migrate Buttons

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4094] opened 2019-09-13 08:31 UTC
🐛 Bug Report

### 🏗 Relevant Components

`<Button/>`

### 😯 Current Behavior

The current Button is still used from Deprecated folder.

### 🤔 Expected Behavior

Should be new Button.

### 👀 Severity

- Low

**Comment by ipanasenko** [comment] 2019-11-12 13:32
I wanted to create new issue, but I will just post it here. When cancel button is disabled, its font size is bigger. Confirm button is fine:
![image](https://user-images.githubusercontent.com/576152/68675931-9c45ad00-0561-11ea-8d9d-a523425de8d7.png)
![image](https://user-images.githubusercontent.com/576152/68675949-a49de800-0561-11ea-86c7-332c15857cbf.png)

Reproducible in Storybook: https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=MessageBoxFunctionalLayout&full=0&addons=0&stories=1&panelRight=0&activeTab=Playground

**Comment by EgoziE** [comment] 2019-11-21 11:00
Check also testkit

**Comment by TalZa1810** [comment] 2020-01-07 12:23
Marik started to work on this in this PR:
https://github.com/wix/wix-style-react/pull/4647

**Comment by shlomitc** [comment] 2020-01-07 12:54
@TalZa1810 but the PR is not yet merged, why did you close the issue?

**Comment by EgoziE** [comment] 2020-01-07 12:56
Because its a duplicate

**Closed** 2020-01-07 13:11 UTC
Labels: <MessageBoxFunctionalLayout/>, Internal
