### ISSUE TITLE
<Tooltip> padding on the sides isn't equal

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#6009] opened 2020-09-21 15:27 UTC
# 🐛 Bug Report

### 🏗 Relevant Components

Tooltip

### 😯 Current Behavior

currently, the tooltip doesn't have equal padding on both sides in certain scenarios.

### 🤔 Expected Behavior

should have the same padding on both sides.

### 👣 Steps to Reproduce

surround anything with this tooltip:
```
<Tooltip content="Click here to hide your visitors’ IP addresses from Google." maxWidth="280px">

</Tooltip>
```
i reproduced it on the WSR playground

  - **WSR version**: `9.12.1`

### 👀 Severity

- Major

**Comment by EgoziE** [comment] 2020-10-18 06:15
Paddings are fine.
@Roeia1 Am I missing something?
![image](https://user-images.githubusercontent.com/35173937/96360094-4b9be400-1122-11eb-9b6c-e3e2caf058fa.png)
![image](https://user-images.githubusercontent.com/35173937/96360096-4e96d480-1122-11eb-828e-ffee18ca0a02.png)

**Comment by Roeia1** [comment] 2020-10-18 06:21
@EgoziE  the CSS padding is the same but there is this extra spacing after the "IP" which looks weird.
my description was a bit confusing 😅

**Comment by EgoziE** [comment] 2020-10-18 08:00
You set it specifically to 280px, so in your particular case the word `addresses` doesn't fit in the area between the word `IP` and the end of the element, therefore it breaks to the second line.
I understand that you want the element to "identify" this line break and resize to less than the maximum, but I'm sorry, this is how `max-width` works natively, once the inner text makes the element wider than the maximum it stops and doesn't shrink again no matter what the actual text looks like.

**Comment by Roeia1** [comment] 2020-11-02 13:04
@EgoziE this is also happening in an <Input> error, regardless of maxWidth
setting errorMessage prop as <Text>content</Text>
it's really weird...
![image](https://user-images.githubusercontent.com/6258872/97870925-5f4b6b00-1d1c-11eb-8c34-7d57053ea40c.png)

**Comment by EgoziE** [comment] 2021-01-19 12:14
That's because there's a 204px max-width by default when you don't provide one.
This is by design. I'm sorry, nothing to fix here, closing.

**Closed by EgoziE** 2021-01-19 12:14 UTC

**Comment by Roeia1** [comment] 2021-01-19 13:29
@EgoziE how can i set max-width in an `<Input>` error tooltip?
there is only `statusMessage` which is a node.
perhaps it's wrapped internally with a tooltip with a fixed width?

**Comment by EgoziE** [comment] 2021-01-19 14:41
There's an open Jira about it - DSM-113
It's low priority for now.
