### ISSUE TITLE
Can not import vanilla testkits when using TSX

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4109] opened 2019-09-16 07:38 UTC
**Reproduction**:
Create a TS file and try to import any of the vanilla testkits

**You will get the following error when trying to compile:**
`(client) /Users/egozi/DEV/cc2019-liran-eran/node_modules/wix-ui-test-utils/dist/src/driver-factory/createDriverFactory.d.ts
Type error: Cannot find module ‘enzyme’.  TS2307`

**Why?**
[`index.d.ts`](https://github.com/wix/wix-style-react/blob/adc9e9adb8035cf8c59a173aa600e6a06557609a/testkit/index.d.ts#L9) is importing stuff from `wix-ui-test-utils`, apparently inside it relies on enzyme.

* Notice this is happening in TS only, in JS the imports of testkits acts differently. 

@argshook

**Comment by shlomitc** [comment] 2019-09-16 16:26
The issue is actually from the second line of the index.d.ts
https://github.com/wix/wix-style-react/blob/adc9e9adb8035cf8c59a173aa600e6a06557609a/testkit/index.d.ts#L10

It imports this file
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-test-utils/src/driver-factory/createDriverFactory.tsx

For some reason, it includes both enzyme and non enzyme creator.
We worked on separating the dependencies to different entries, exactly for that reason
https://github.com/wix/wix-ui/tree/master/packages/wix-ui-test-utils/src
If this file is not split to different technologies (enzyme, vanilla) in one of these folders - let’s do it

**Comment by simast** [comment] 2019-11-19 14:28
Fixed by @mosheKerbel with https://github.com/wix/wix-ui/pull/1528

**Closed by simast** 2019-11-19 14:28 UTC
Labels: Priority:Major, testkit:bug
