### ISSUE TITLE
<Notification /> animation is a bit poor

### ISSUE THREAD

**Issue by BnayaZil** [wix/wix-style-react#4922] opened 2020-01-26 09:09 UTC
# 🐛 Bug Report

### 🏗 Relevant Components
`<Notification/>`

### 😯 Current Behavior
Entering- The content suddenly appear then the animation increase the body size.
Leaving- (maybe this is the expected behavior) the text leave before the body.

### 🤔 Expected Behavior
In case the asymmetry between the text and the body is the expected behavior I would expect the text to enter as he left.

In general, I would expect the entire notification component to behave as one unit, enter, and leave all in one piece.

### 👣 Steps to Reproduce
  - **WSR version**: `7.37.1`

### 👀 Severity
- Low

P.S- could be nice to have a snackbar component as part of WSR.

**Comment by shlomitc** [comment] 2020-01-27 09:01
@milkyfruit - what is your input regarding this? I remember we worked to define the animation correctly, so maybe it's just an intended behavior and not a bug?

**Comment by milkyfruit** [comment] 2020-01-27 15:39
@shlomitc this is a quite old animation. Closing works fine, I agree opening looks buggy, though it doesn't look critical.

@BnayaZil if this is not critical,  I suggest to wait until we have a proper animation library and then all the components will be reviewed.

**Comment by BnayaZil** [comment] 2020-01-28 06:52
> @BnayaZil if this is not critical, I suggest to wait until we have a proper animation library and then all the components will be reviewed.

@milkyfruit if as part of your plan you will use the animation library to fix the notification so, sure I can wait, if I will have to switch context back to my product to implement a new animation library I think u rather fix what I and probably many others already use first.

**Comment by shlomitc** [comment] 2020-01-28 09:48
@milkyfruit - what animation library are you talking about? do you mean in the UX-level definition? I don't think it should be a blocker for fixing the animation lag. You can just provide the animation definition and @BnayaZil can fix accordingly.

**Comment by ZilvinasMaciulis** [comment] 2020-01-28 11:26
Hi People

Here is an example of how it should animate in relation with the content below. 
Duration in/out - 300ms
Easing - 0.25, 0.1, 0.25, 1

![Notification](https://user-images.githubusercontent.com/44393332/73259811-403e0c80-41d1-11ea-89fa-ef41c98e1067.gif)

**Comment by milkyfruit** [comment] 2020-01-28 11:43
> @milkyfruit - what animation library are you talking about? do you mean in the UX-level definition?

@shlomitc yes, all the components are being reviewed to understand what animation classes we need. Until then, @ZilvinasMaciulis shared the quick fix solution.

**Comment by shlomitc** [comment] 2020-01-28 12:14
@BnayaZil - we'll be happy to have a PR for this

**Comment by BnayaZil** [comment] 2020-01-28 12:35
Hoo... I never meant to contribute this one 😊 
I'm actually pretty shitty when it comes to animations.

**Comment by shlomitc** [comment] 2020-01-28 12:41
It can be a great opportunity to do so and learn, we'll be happy to assist

**Comment by BnayaZil** [comment] 2020-01-28 12:47
k, I will take this one.
I will be in touch with u.

**Closed** 2020-06-29 17:42 UTC
Labels: <Notification/>, Bug
