### ISSUE TITLE
`<MultiSelect/>` - valueParser not used consistently

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2504] opened 2018-11-27 06:59 UTC
Continuing #2503 ,

## The issue

For each component which extends `InputWithOptions` there is a slightly different use of `valueParser`.

Components are:
- Dropdown
- MultiSelect
- MultiSelectCheckbox
- AutoComplete

## Solution
We can go over implementations and make them consistent with each other.

Personally, I think `valueParser` should not exist.
I will open an API suggestion for generic Dropdown option API.

But basically, I think
```js
<InputWithOptions>
  <Option value="whatever string value">
     Blue towel
  </Option>
</InputWithOptions>
```

- `value` acts as the ID of the option, and the "value" of a Dropdown should be that value, or in case of MultiSelect, the "value" should be a list of the `value`. It means that `onSelect`  callbacks pass the `value` only.

**Comment by shlomitc** [comment] 2018-12-11 12:30
Instead of introducing a completely new API I suggest to have it just as an option configuration.

An example for options:
```js
const options = [
  { id: 0, value: 'Great appartment 🏡' },
];
```

which can be extended to:
```js
const options = [
  { id: 0, value: 'Great appartment 🏡', label: 'Great appartment' },
];
```

anyway, as this is a suggestion for solution, I think the issue is in the previous discussion, so let's keep it in one place. closing

**Closed by shlomitc** 2018-12-11 12:30 UTC
