### ISSUE TITLE
disabled breadcrumb should have ability to select their text

### ISSUE THREAD

**Issue by aryelu** [wix/wix-style-react#823] opened 2017-09-14 08:32 UTC
### Priority:
- [ ] Blocker
- [x] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1.set breadcrumbs with disable attribute

### Expected behavior:
Disable breadcrumb text should be selectable
![image](https://user-images.githubusercontent.com/11705492/30419799-56d12e0a-9940-11e7-9722-1cc720a359d0.png)

**Comment by YuriyFedorov** [comment] 2017-10-02 09:52
Hey

any updates on that one ?

**Comment by lbelinsk** [comment] 2017-10-02 12:24
Will try to get to it this week - next week

**Comment by lbelinsk** [comment] 2017-10-02 17:42
Hey, not sure what is the problem.

I modified the first item in the screenshot:

{id: '1', value: 'first item', disabled: true}

And it is selectable:
![image](https://user-images.githubusercontent.com/18248989/31090974-2fcd222a-a7b2-11e7-8b0a-a8c98f0a5020.png)


Maybe you are passing customItems?

**Comment by aryelu** [comment] 2017-10-03 05:11
Here's my props
```json
{
  "dataHook": "contacts-breadcrumbs",
  "items": [
    {
      "id": 0,
      "value": "Home"
    },
    {
      "id": 1,
      "value": "Contact List"
    },
    {
      "id": 2,
      "value": "100",
      "disabled": true
    }
  ],
  "activeId": 2,
  "size": "medium",
  "onClick": "[function ]",
  "theme": "onGrayBackground"
}
```

**Comment by lbelinsk** [comment] 2017-10-03 06:58
So looks like the only thing that is different when I reproduce it is that you also select the disabled item as the activeId.

1. It is still working for me.
![image](https://user-images.githubusercontent.com/18248989/31113155-87af3fbe-a820-11e7-9988-5d8f34c991ed.png)

![image](https://user-images.githubusercontent.com/18248989/31113163-8f09e5ac-a820-11e7-9f1b-d9a9188d30c0.png)

![image](https://user-images.githubusercontent.com/18248989/31113321-64c6cb9c-a821-11e7-8f04-ad692465b1bc.png)


2. Why would you select the actieId as the disabled one. Can't you can remove the disabled prop?

**Comment by lbelinsk** [comment] 2017-10-03 06:59
I suggest you try to reproduce it on story book. if you are able to reproduce it (since I can't) send me the branch or even share your screen.

**Comment by lbelinsk** [comment] 2017-10-15 12:22
@aryelu all good?
Can I close this?

**Comment by lbelinsk** [comment] 2017-10-20 10:04
@aryelu I see the problem.
You can highlight the text but only if the first click is starting from the side far from the item.
Is there any chance you can help with a pr for this?
If not we will take care of it. 
Will send you a video on slack

**Comment by lbelinsk** [comment] 2017-11-01 09:44
@aryelu according to our design spec, we shouldn't allow highlighting text of the breadcrumb item (even if it is the active item).

Closing this, your UX is welcome to talk to Ben Benhorin
@wuwa

**Closed by lbelinsk** 2017-11-01 09:44 UTC
Labels: Breadcrumbs
