### ISSUE TITLE
<ImageViewer/> - add visual testing for new states

### ISSUE THREAD

**Issue by gilmeir** [wix/wix-style-react#4164] opened 2019-09-25 13:42 UTC
* Hover menu (with update / remove buttons)
* Loader
* Rendering previous image in the background of the loader while loading the new image.

**Comment by TalZa1810** [comment] 2020-01-19 12:54
The driver `hover` function doesn't work as expected when trying to convert the tests to visuals.
The `hover` function is used in the actual driver. I didn't want to change the existing function in order not to break existing tests:
https://github.com/wix/wix-style-react/blob/master/src/ImageViewer/ImageViewer.uni.driver.js#L13

Therefore, more research needs to be done in order to resolve this. Commits for reference:
https://github.com/wix/wix-style-react/pull/4823/commits/c2956c3f691d598a6efa1ab4ba89be6e844afe52
https://github.com/wix/wix-style-react/pull/4823/commits/bc3c69436c2ec917189577b4d5e714572d3001d5

Meanwhile, I'm merging the changes that are relevant but the issue is still open.

**Comment by shlomitc** [comment] 2020-04-16 06:26
won't be fixed

**Closed by shlomitc** 2020-04-16 06:26 UTC
Labels: <ImageViewer/>, Docs
