### ISSUE TITLE
addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by skyiea** [wix/wix-style-react#1499] opened 2018-03-02 10:43 UTC
### Summary:
I'm using `DataTable` component. When I simulate `clickRow` in my tests, I get this error:
```
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
I've create repo with reproducible issue: https://github.com/wix-private/wsr-datatable-testkit-issue
It blocks me from writing any kind of tests that interact with `DataTable`.

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

**Comment by mariafeldman** [comment] 2018-04-15 15:04
I have the same issue with Page.Header component. It blocks all my integration tests for entire page

**Comment by shlomitc** [comment] 2018-04-15 16:29
![image](https://user-images.githubusercontent.com/6093192/38780668-00d1e882-40e3-11e8-8545-7dfaedccef19.png)
@skyiea - It passes on my machine
@mariafeldman - can you please elaborate more? how can reproduce it?

**Comment by mariafeldman** [comment] 2018-04-16 06:46
@shlomitc, just try to add a test for component with <Page.Header> component. 
I have a test which failed with the error "addComponentAsRefTo(...): Only a ReactOwner can have refs". When I remove Page.Header from Page, the error disappears. There is a ignored test 'should send bi when click on create' in coupons-client project where the error is reproduced

**Comment by skyiea** [comment] 2018-04-19 08:25
@shlomitc - example is passing on my machine too now. Not sure what've changed. Will investigate when will have spare time.
I'm still getting this error in my project, so the issue persists.

**Comment by skyiea** [comment] 2018-04-19 08:38
Strange thing to note: secondary WSR install fixes the issue. @mariafeldman you can temporarily try this approach to avoid skipping tests. What I'm doing is:
```
"postinstall": "npm run fix-wsr",
"fix-wsr": "npm i wix-style-react --no-save"
```

**Comment by argshook** [comment] 2018-04-19 08:45
wait wot?

if installing wsr once again fixes issue, then i would guess it's a matter of versions, deduplication of modules or something.

would it be possible to see a diff of logs of `npm install` and later `npm install wix-style-react --no-save`?

**Comment by skyiea** [comment] 2018-04-19 08:54
@argshook like 2 package-locks?

**Comment by argshook** [comment] 2018-04-19 09:02
nono, roughly something like
`npm install > output.log`
then later `npm install wix-style-react --no-save > second-output.log`

and compare those, to see what versions get installed.
i may be shooting blanks, but if installing wsr again fixes issue, there must be something with npm install

**Comment by shlomitc** [comment] 2018-04-21 17:13
I merged the relevant PR.
@mariafeldman - can you please try to reinstall your project locally and see if it solved it?
(make sure you delete `package-lock.json` and `yarn.lock`)

**Comment by mariafeldman** [comment] 2018-05-17 08:04
Now it works for me, thanks!

**Comment by mariafeldman** [comment] 2018-05-17 09:02
I'm closing the issue

**Closed by mariafeldman** 2018-05-17 09:02 UTC
Labels: bug
