### ISSUE TITLE
Tooltip won't work on a disabled button

### ISSUE THREAD

**Issue by shahafan** [wix/wix-style-react#832] opened 2017-09-17 09:13 UTC
### Summary:
When trying to add a tooltip to a disabled button it doesn't work.

    <Tooltip textAlign="left" placement="left" alignment="center" content="test" maxWidth="250px">
        <Button theme="fullblue" onClick={() => console.log('clicked')} disabled={true}>
            Text
       </Button>
    </Tooltip>

### Priority:
- [x] Normal

### Expected behavior:
tooltip should be displayed when hovering

### Relevant Components:
Tooltip , Button

**Comment by lbelinsk** [comment] 2017-12-19 19:07
@amiryonatan could you please check that in the new planned Tooltip we don't have this issue. If so, you can close this one

**Comment by Faradey27** [comment] 2018-06-19 12:06
@lbelinsk looks like the problem is related to Button and not to Tooltip

https://github.com/wix/wix-style-react/blob/master/src/ButtonLayout/ButtonLayout.scss#L823 - root of problem, i am working on fix

**Comment by Faradey27** [comment] 2018-06-26 08:11
https://github.com/wix/wix-style-react/pull/1855

**Closed** 2018-07-19 22:14 UTC
Labels: Tooltip, bug
