### ISSUE TITLE
[React 16] Tooltip doesn't work

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#865] opened 2017-09-27 10:05 UTC
Hey, guys.

Upgraded to React 16 only to find out that Tooltip doesn't work with it.
And other components that depend on Tooltip, like PopoverMenu.

**Comment by argshook** [comment] 2017-11-06 16:11
@ipanasenko i merged #1053 which goes over this. please reopen if you still encounter the issue

**Comment by lbelinsk** [comment] 2017-12-19 19:05
@amiryonatan if we are going to use react-popper, do you know if we are ok for react16?

**Comment by lbelinsk** [comment] 2017-12-19 19:27
Great. leaving this open for now. hopefully, we will change the tooltip implementation in the close future

**Comment by yakirn** [comment] 2018-04-23 07:45
Hi
Any updates on this? Really want to switch to React 16 😬

**Comment by ipanasenko** [comment] 2018-06-18 16:13
Look good. Thanks!!

**Comment by argshook** [comment] 2018-06-25 14:37
unfortunately have to reopen this, previous fix surfaced other issues :(
https://github.com/wix/wix-style-react/commit/f0b6e5b101c904a82c5f8ac342ff25794d58ca39

**Comment by shlomitc** [comment] 2018-07-19 22:13
A Fix was introduced again here https://github.com/wix/wix-style-react/blob/master/CHANGELOG.md#461---2018-07-02
please try and check if it works for you

**Comment by ipanasenko** [comment] 2018-07-20 11:33
No errors, but no tooltip either

**Comment by katmai7** [comment] 2018-07-27 09:56
Hi, I have an issue with Tooltip/PopoverMenu too(looks like it the same).

I use React 16.
My code:
```
<PopoverMenu placement="bottom">
  <PopoverMenuItem
  onClick={handleNodeEdit.bind(null, node, path)}
  text="Edit"
  />
</PopoverMenu>
```
Note: I use popover in a scrollable list

The problem is there is no top and left properties.
![How popover looks like in the DOM](https://user-images.githubusercontent.com/3172108/43314482-bb66cbe6-919b-11e8-8139-0b9ad72784ef.png)

The Popover component also has `appendToParent` but it doesn't work properly with `placement` prop.

**Comment by shlomitc** [comment] 2019-01-20 18:42
the issue should be resolved now. please re-open if occurs on latest version (5.24.0)

**Closed by shlomitc** 2019-01-20 18:42 UTC
Labels: General, Tooltip, bug
