### ISSUE TITLE
Google Address Input should check not to setState when the component is unmounted

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1240] opened 2017-12-08 18:14 UTC
This component has async stuff.
Once you start the async method, the component might get unmounted, and once the async operation ends, the callback with the `setState`, we might end up doing setState on an unmounted component.

We should add a condition to the callback to check whether the component is still in the dom or not.

**Comment by lbelinsk** [comment] 2017-12-19 00:25
@gonengar will it be possible to fix this on the fly while you are touching this component?

**Comment by shlomitc** [comment] 2019-01-29 19:57
couldn't reproduce, closing until pops again

**Closed by shlomitc** 2019-01-29 19:57 UTC
Labels: GoogleAddressInput
