### ISSUE TITLE
<ColorInput /> icon blurred on Edge

### ISSUE THREAD

**Issue by MSiliunas** [wix/wix-style-react#3513] opened 2019-06-04 07:04 UTC
# 🐛 Bug Report

### 🏗 Relevant Components

- `<ColorInput />`
- `<Swatches />`

### 😯 Current Behavior

No color icon is blurred on Edge browser
![image](https://user-images.githubusercontent.com/6944305/58858246-d441ed80-86af-11e9-906a-37d2dbb4cc5b.png)

### 🤔 Expected Behavior

Should be displayed as in all browsers.

### 👣 Steps to Reproduce

Tested and occurred on:
```
Windows 10
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
```

  - **WSR version**: `6.24.0`

### 👀 Severity

- Low

**Comment by argshook** [comment] 2020-01-08 06:03
@MSiliunas please check, is this still relevant? I'm unable to reproduce on wsr@7.30.0

this is what i see:

![2020-01-08-080019_screenshot](https://user-images.githubusercontent.com/4284659/71954134-f3c46a00-31ec-11ea-908e-c698d035423f.png)

please note that i used edge version 44

![2020-01-08-075923_screenshot](https://user-images.githubusercontent.com/4284659/71954164-09d22a80-31ed-11ea-9c21-eac85f359880.png)

**Comment by argshook** [comment] 2020-01-08 09:52
CC @kranux, maybe you're aware if it's still relevant

**Comment by kranux** [comment] 2020-01-08 09:59
@argshook Sorry, I do not know, and do not have tools to verify at the moment :) Let's talk again next week :)

**Comment by argshook** [comment] 2020-01-08 10:00
closing for now

please feel free to reopen if it comes up as still relevant!

**Closed by argshook** 2020-01-08 10:00 UTC
Labels: <ColorPicker/>, Bug, Priority: Low
