### ISSUE TITLE
<ButtonLayout> `outlined` theme uses wrong colors

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2348] opened 2018-10-18 06:58 UTC
# Bug Report

### Reported component
https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.0%20ButtonLayout&full=0&addons=0&stories=1&panelRight=0

### Current Behavior
`<ButtonLayout>` when property `theme` is set to `outlilined` shows wrong text color on hover and click:
![image](https://user-images.githubusercontent.com/1684587/47136262-d3dd1980-d2bb-11e8-9bc3-55942c6c0a20.png)

**EDIT**: The bug appears only when these sizes are set: `height: small` and `height: x-small`

### Expected Behavior
Button's tex color should be white (D80) on hover and click events.

### Severity
- [ ] Critical
- [x] Major
- [ ] Low

### Specs

https://zpl.io/aRq9ZKv

Default:
![image](https://user-images.githubusercontent.com/1684587/47136292-f111e800-d2bb-11e8-81bf-91941b0c5eb6.png)
Mouse Hover:
![image](https://user-images.githubusercontent.com/1684587/47136298-f5d69c00-d2bb-11e8-9f0a-335bef43671c.png)
Mouse Click:
![image](https://user-images.githubusercontent.com/1684587/47136306-f96a2300-d2bb-11e8-8d3c-3c6e9d93238e.png)
Disabled:
![image](https://user-images.githubusercontent.com/1684587/47136290-ece5ca80-d2bb-11e8-80af-71aeac00ebd9.png)

**Comment by yardnsm** [comment] 2018-10-18 08:53
Couldn't reproduce, button looks good to me in the story. Where are you seeing it?

**Comment by shlomitc** [comment] 2018-10-18 12:21
@yardnsm 
I think he is looking at the `<SectionHelper/>` component with the `warning` appearance prop
https://wix-wix-style-react.surge.sh/?selectedKind=8.%20Notification%20Bars&selectedStory=8.7%20SectionHelper&full=0&addons=0&stories=1&panelRight=0

**Comment by milkyfruit** [comment] 2018-10-18 14:40
@yardnsm @shlomitc forgot to mentioned that bug appears only on `height: small` and `height: x-small` sizes.

It's visible in both `<ButtonLayout/>` and `<SectionHelper/>` playgrounds.

**Comment by yardnsm** [comment] 2018-10-21 11:07
Resolved in https://github.com/wix/wix-style-react/pull/2350

**Closed by yardnsm** 2018-10-21 11:07 UTC
Labels: Button, bug
