### ISSUE TITLE
PopoverMenu stays stock on screen when scrolling  

### ISSUE THREAD

**Issue by nofarcohav** [wix/wix-style-react#2920] opened 2019-02-07 12:23 UTC
# 🐛 Bug Report

### 🏗 Relevant Components

```jsx
<PopoverMenu
  placement="left"
  dataHook="manage-apps-inner-section-context-menu"
  buttonTheme="icon-standardsecondary"
>
  <PopoverMenuItem text={'Need support?'} disabled />
  <PopoverMenuItem
    onClick={() => this.handleSupportClick(app, index)}
    text={getSupportText(app)}
  />
  <PopoverMenuItem
    icon={
      <svg height="1" width="160">
        <line x2="160" stroke="#dfe5eb" strokeWidth="2" />
      </svg>
    }
  />
  {shouldShowAddAgain(app) && (
    <PopoverMenuItem
      icon={<Add />}
      text={'Add Again'}
      onClick={() => this.handleAddAgainClick(app, index)}
    />
  )}
  <PopoverMenuItem
    icon={<Delete />}
    text={this.getDeleteText(app)}
    onClick={() => this.handleDeleteClick(app, index)}
  />
</PopoverMenu>
```

### 😯 Current Behavior

the menu stays open and sticks to other components

...

### 🤔 Expected Behavior

the menu will close / stays at it's original place

...

### 👣 Steps to Reproduce

to reproduce go to editor -> app market-> manage apps -> open app context menu 0> scroll
tried using appendToParent prop but it didn't help

- **WSR version**: `5.15.1`
- **Yoshi version**: `1.2.0`

### 👀 Severity

Major

**Comment by shlomitc** [comment] 2019-02-07 12:24
please add a code snippet reproducing the issue

**Comment by shlomitc** [comment] 2019-02-10 22:35
Looks like the current position mechanism of the component is not supporting you custom scroll use-case
We're planning to change the implementation to use the new `DropdownBase` component which solves these kinds of issues, but it will take a while until we will get to it since it's a complicated issue with a big effort.

**Comment by mosheKerbel** [comment] 2019-05-31 11:47
PR in progress (https://github.com/wix/wix-style-react/pull/3485)
once merged we can close this issue and use the solution defined here (https://github.com/wix-private/wsr-issues/issues/407) in the last comment.

**Comment by mosheKerbel** [comment] 2019-06-12 08:09
@nofarcohav new PopoverMenu is merged.
It solves your issue.

**Closed** 2019-06-12 08:10 UTC
Labels: PopoverMenu, type:bug

**Comment by nofarcohav** [comment] 2019-06-12 09:02
Hi, do I need to add some new prop? because it's not working

**Comment by mosheKerbel** [comment] 2019-06-12 09:13
let's talk on Slack where you could share your screen
i'll be available at 13:30 after launch.
