### ISSUE TITLE
Input component is missing a counter

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#1664] opened 2018-04-10 16:16 UTC
### Summary:
The InputArea component has the option to display a counter (current length / max length) 

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Expected behavior:
The Input component should have a similar counter prop like the InputArea has

### Relevant Components:
Input, InputArea

**Comment by milkyfruit** [comment] 2018-04-18 08:28
Text Field (Input),
Text Area (incl. Rich Text Area),
Text Field With Selection

Has character counter feature by design.
![image](https://user-images.githubusercontent.com/1684587/38920291-986aa43a-42fb-11e8-863f-133a3985cf7d.png)

[Indexed Specs.](zpl.io/anRW6Ja)
[behaviour specs](zpl.io/2Egjola)

**Comment by shlomitc** [comment] 2018-07-12 23:40
Hey, we (Arijus) lately added the `FormField` component which is a replacement for the `TextField` composition.
It allows you to compose any type of component (not only input) and also gives you the ability to display the counter, as requested.

See how it works here:
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0

Choose `Input with char counter` from the `children*` list and type something

![image](https://user-images.githubusercontent.com/6093192/42664915-04ad5d4e-8646-11e8-8054-620bc57d5458.png)

Can you please try it out and tell us if it fit your needs? if so, we will declare this component as the right solution for compositions.

**Comment by mozesoron** [comment] 2018-07-15 08:08
@shlomitc it seems fine but I can't see the full example of how the counter is added. need to fix the story.

**Comment by shlomitc** [comment] 2018-07-15 09:37
Take a look in the top section in that page, you will find a code example for the counter

**Comment by mozesoron** [comment] 2018-07-15 09:44
@shlomitc design wise looks fine. what I mean is that I cant see the code in the story.

**Comment by shlomitc** [comment] 2018-07-15 10:58
![d4af6236-57cc-432f-8920-228545fcd0b5](https://user-images.githubusercontent.com/6093192/42733263-0e814180-8837-11e8-9692-313133c57b85.png)

**Comment by shlomitc** [comment] 2018-07-27 08:14
No further comments so I’m closing this one. If any issue is raised, please reopen

**Closed by shlomitc** 2018-07-27 08:14 UTC
Labels: Input, feature request
