### ISSUE TITLE
Text inside is getting selection style by opening dropdown 

### ISSUE THREAD

**Issue by CrispusDH** [wix/wix-style-react#5531] opened 2020-06-09 15:33 UTC
# 🐛 Bug Report

### 🏗 Relevant Components

[Dropdown](https://wix-style-react.now.sh/?path=/story/components-api-components--dropdown)

### 😯 Current Behavior

By clicking on DropDown the text inside is getting selection style

![](https://media.giphy.com/media/JpkPLmo2DGvND09A2o/giphy.gif)

### 🤔 Expected Behavior

By clicking on DropDown the text inside does not change style

![](https://media.giphy.com/media/kAtQOW8YjNYu9PB6af/giphy.gif)

### 👣 Steps to Reproduce

**Click** on a text for opening Dropdown

  - **WSR version**: `latest`
  - **Yoshi version**: not relevant

### 👀 Severity

- Low

**Comment by EgoziE** [comment] 2020-06-09 15:42
Duplicate of https://github.com/wix/wix-style-react/issues/4554

**Closed by EgoziE** 2020-06-09 15:42 UTC
Labels: <Dropdown/>, Bug, Priority: Low
