### ISSUE TITLE
`<SortableList/>` - is lagging when dropping outside the boundaries of drop container

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4416] opened 2019-10-29 13:20 UTC
# 🐛 Bug Report

### 🏗 Relevant Components

`<SortableList/>`

### 😯 Current Behavior

See it how it gets stuck.
![SortableListlag](https://user-images.githubusercontent.com/8919190/67770659-7e575300-fa5f-11e9-95de-434142bf4ff7.gif)

### 🤔 Expected Behavior

It should be smooth.

### 👣 Steps to Reproduce

Check storybook example: https://wix-style-react.now.sh/?selectedKind=WIP%2FDrag%20And%20Drop%2FSortableList&selectedStory=Multi%20Area%20List&full=0&addons=0&stories=1&panelRight=0

### 👀 Severity

- Critical

**Comment by argshook** [comment] 2019-10-30 12:21
Just fyi, this i can't reproduce on linux neither on chrome nor firefox

**Comment by mykas** [comment] 2019-10-30 12:23
Noticed this only on Mac

**Comment by EgoziE** [comment] 2020-10-25 11:28
Won't be fixed - closing

**Closed by EgoziE** 2020-10-25 11:28 UTC
Labels: <SortableList/>, Bug
